filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/cowrie/cowrie.json
    - /var/log/pyrdp_output/mitm.json
    - /var/log/pyrdp_scenario_output/output.json
    - /var/log/ddospot_output/genericpot.log
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.expand_keys: true

output.logstash:
  hosts: ["logstash:5044"]

http.enabled: true
http.host: 0.0.0.0
